table Data_Dictionary
	lineageTag: dadc86ec-e053-4ab8-a7ed-7d402a3c0aa3

	column Table
		dataType: string
		lineageTag: d99cdec1-9154-440b-a7e4-cf9b998d44ec
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Field
		dataType: string
		lineageTag: 342b84b5-f858-442f-8cbb-2c87446acae6
		summarizeBy: none
		sourceColumn: Field

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 34c9c4f0-61b2-4548-a2f6-1899ff46d0f0
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Data_Dictionary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Projects\Kaggle analysis\Global_Electronics_Retailer\Data_Dictionary.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Table", type text}, {"Field", type text}, {"Description", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

