table Products
	lineageTag: fcd83105-23f5-47a9-854f-7a9ee484b656

	column ProductKey
		dataType: string
		lineageTag: 06cb26ce-e06b-4755-8234-0d1a6aa1af07
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: ea9090b9-ac75-46a1-a098-1afb8cd393e4
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: fc2a34a7-c356-4b5c-8db6-30f6b1eb6e05
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: c7965bd6-c713-45b2-8f1e-ca0a39116df5
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost USD'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d9cfa880-d4d2-45bc-b4f9-250e80d2878d
		summarizeBy: none
		sourceColumn: Unit Cost USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Price USD'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: be3fe139-9732-45ea-8f32-c113b9cd40fa
		summarizeBy: none
		sourceColumn: Unit Price USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SubcategoryKey
		dataType: string
		lineageTag: b28ace01-1a88-43e8-ba07-18d6f9400ed6
		summarizeBy: none
		sourceColumn: SubcategoryKey

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 53e80823-fb58-4367-8ac5-f648239a94e6
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column CategoryKey
		dataType: string
		lineageTag: ec62c7be-4c45-4389-aaaf-adc012bef0e5
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 22c886ac-ad9c-4af1-bd00-d5aad9c5e166
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Projects\Kaggle analysis\Global_Electronics_Retailer\Products.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", type text}, {"Product Name", type text}, {"Brand", type text}, {"Color", type text}, {"Unit Cost USD", Currency.Type}, {"Unit Price USD", Currency.Type}, {"SubcategoryKey", type text}, {"Subcategory", type text}, {"CategoryKey", type text}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

