table Sales
	lineageTag: 28f0c59d-e3f9-4397-a972-578a8c748121

	measure Profit =
			
			SUMX(Sales,
			    VAR UnitProfit = RELATED(Products[Unit Price USD]) - RELATED(Products[Unit Cost USD])
			    VAR ExchangeRate = RELATED(Exchange_Rates[Exchange])
			    RETURN
			    Sales[Quantity] * UnitProfit * ExchangeRate
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7a04bdfd-6bec-4574-bca1-88352919500e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Online Store Profit' = CALCULATE([Profit],Sales[StoreKey]="0")
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 62b0e549-87ab-40bc-a656-4e6a1c37c1f6

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales Count' = COUNT(Sales[Order Number])
		formatString: 0
		lineageTag: dee915d2-24bc-4041-be71-7b1d234810aa

	measure 'Online Sales Count' = CALCULATE(Sales[Sales Count],Sales[StoreKey]="0")
		formatString: 0.00
		lineageTag: 1a09d628-bd8f-41dc-92de-da90fdbfe4a1

	measure 'Returning Customers' = COUNTROWS(FILTER(VALUES('Sales'[CustomerKey]),CALCULATE(COUNT('Sales'[Order Number])) > 1))
		formatString: 0
		lineageTag: 1a405685-8c7e-4f77-985d-75bd94a69564

	column 'Order Number'
		dataType: string
		lineageTag: cd7e60dc-f719-4ec7-b8da-3ad7169a1d84
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column 'Line Item'
		dataType: int64
		formatString: 0
		lineageTag: 4e753017-ff5d-4057-8b4e-efd0cf672eee
		summarizeBy: sum
		sourceColumn: Line Item

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b70e4816-652b-489f-81c1-1ab0bbbc9fbb
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 36e1edcd-b3af-4019-bbca-d60223037296
			defaultHierarchy: LocalDateTable_d7eabbf8-5af9-47ae-8a91-26bf205ee236.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 119cf472-7fff-4b54-94e2-e27db5e02dda
		summarizeBy: none
		sourceColumn: Delivery Date

		variation Variation
			isDefault
			relationship: 0c9c626d-74ed-423b-aea1-89787810d888
			defaultHierarchy: LocalDateTable_befbf127-f836-40e0-b9c4-6eb703f9e049.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: string
		lineageTag: dbc4822f-ee00-4abd-a15d-eb50ac1ebe10
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: string
		lineageTag: 63c8bc1a-d9a4-4817-a712-46745d90c1ba
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: string
		lineageTag: 55f3e1a5-a2cc-4aa0-917b-571f3e806804
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 39b87567-61ce-49b4-9117-ccfe3830c9a3
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Currency Code'
		dataType: string
		lineageTag: 0ba1f6f7-e901-42bf-b7ba-e97c54bac152
		summarizeBy: none
		sourceColumn: Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Date Exchange' = Sales[Currency Code] &"-"& Sales[Order Date].[Date]
		lineageTag: 6701a382-00e0-4640-b62d-34005d05a481
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Online = if(Sales[StoreKey]="0","Online","Offline")
		lineageTag: 2c678d83-80e7-45b4-9b0a-090ec81c235c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Location = IF(Sales[StoreKey]="0",RELATED(Customers[State]),RELATED(Stores[State]))
		lineageTag: 34444966-3e0a-4370-accd-6188c94f0311
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Location city' = IF(Sales[StoreKey]="0",RELATED(Customers[City]),RELATED(Stores[State]))
		lineageTag: 62c9cff9-40d8-4e30-a8f2-59909e42dc18
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data Projects\Kaggle analysis\Global_Electronics_Retailer\Sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order Number", type text}, {"Line Item", Int64.Type}, {"Order Date", type date}, {"Delivery Date", type date}, {"CustomerKey", type text}, {"StoreKey", type text}, {"ProductKey", type text}, {"Quantity", Int64.Type}, {"Currency Code", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

